### ISSUE TITLE
【レビュー依頼】DB設計

### ISSUE THREAD

**Issue by daikirokuyama** [we-b/PHP_Mooovi#3]
## 実装機能及びその順序
※実装の詳細は担当者が逐次考え相談する

### 1. 映画作品の一覧/保存/詳細/検索
- 映画作品の投稿はスクレイピングで実装する

### 2. ユーザ機能
- サインアップ
- ログイン
- アバター画像のアップロード
- マイページ

### 3. レビューの投稿
- 数値で評価ができ、★で表示される

### 4. ランキング機能
- 映画額品がreview数を基準に上位5件ランキングされた状態で表示される

### users
ユーザー基本情報: avatarカラム以外はデフォルト

| Field          | Type             | Null | Key | Default | Extra          |
|:----------:|:------------:|:----:|:---:|:--------:|:----------:|
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255)     | NO   |     | NULL    |                |
| email          | varchar(255)     | NO   | UNI | NULL    |                |
| password       | varchar(60)      | NO   |     | NULL    |                |
| remember_token | varchar(100)     | YES  |     | NULL    |                |
| created_at     | timestamp        | YES  |     | NULL    |                |
| updated_at     | timestamp        | YES  |     | NULL    |                |
| avatar         | varchar(255)     | NO   |     | NULL    |                |

#### association
- hasMany: reviews

### password_resets
パスワードリセット: すべてデフォルト

| Field          | Type             | Null | Key | Default | Extra          |
|:----------:|:------------:|:----:|:---:|:--------:|:----------:|
| email      | varchar(255) | NO   | MUL | NULL              |                             |
| token      | varchar(255) | NO   | MUL | NULL              |                             |
| created_at | timestamp    | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |

### products
映画作品をスクレイピングして保存するテーブル

| Field          | Type             | Null | Key | Default | Extra          |
|:----------:|:------------:|:----:|:---:|:--------:|:----------:|
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| title      | varchar(255)     | NO   |     | NULL    |                |
| image_url  | text             | NO   |     | NULL    |                |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |
| director   | varchar(255)     | NO   |     | NULL    |                |
| detail     | text             | NO   |     | NULL    |                |
| open_date  | varchar(255)     | NO   |     | NULL    |                |

#### association
- hasMany: reviews

### reviews
映画情報に対してレビューを投稿するテーブル

| Field          | Type             | Null | Key | Default | Extra          |
|:----------:|:------------:|:----:|:---:|:--------:|:----------:|
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| rate       | int(11)          | NO   |     | NULL    |                |
| review     | text             | NO   |     | NULL    |                |
| product_id | int(11)          | NO   | MUL    | NULL    | foreign_key: true |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |
| user_id    | int(11)          | NO   | MUL    | NULL    | foreign_key: true |

#### association
- belongsTo: users
- belongsTo: products

**Comment by DAIHI** [comment]
LGTM
